// Generates a Photoshop ExtendScript (.jsx) file the photographer runs locally — Photoshop then
// builds the page as a real, editable PSD on their own machine, matching photos to files by their
// original filename in a folder they pick. Beta: only plain cover-fit photo placement (crop +
// focal point) is implemented so far. Masks, borders, shadows, rotation, and text elements are not
// yet translated into script instructions — see resolveAlbumJsxPage's skip-tracking for why.

export type AlbumJsxPageElement = {
  photoId: string;
  filename: string;
  xPct: number;
  yPct: number;
  widthPct: number;
  heightPct: number;
  focalX: number;
  focalY: number;
};

export type AlbumJsxPageData = {
  pageLabel: string;
  widthPx: number;
  heightPx: number;
  dpi: number;
  elements: AlbumJsxPageElement[];
  skippedTextCount: number;
  skippedExtrasCount: number; // photo elements placed, but with an unsupported extra (mask/border/rotation/shadow) ignored
};

// U+2028/U+2029 are valid inside a JS string literal but several older JS engines (ExtendScript's
// among them) treat them as line terminators when they land in source text via a naive template
// literal — escaping them keeps Hebrew filenames (or any text) from ever producing that landmine.
function safeJsonLiteral(value: unknown): string {
  return JSON.stringify(value).split("\u2028").join("\\u2028").split("\u2029").join("\\u2029");
}

export function generateAlbumPageJsx(data: AlbumJsxPageData): string {
  const pageJson = safeJsonLiteral(data);
  return `#target photoshop
// Generated by photographer-flow — builds this album page as a real Photoshop document.
//
// How to run: open Photoshop first, then use File > Scripts > Browse... and pick this file.
// IMPORTANT: don't double-click the file itself — .jsx is also After Effects' script extension, so
// on most computers double-clicking hands it to whichever of the two the OS considers the default,
// which is often the wrong one. File > Scripts > Browse always runs it in Photoshop regardless of
// that file-association setting. You'll be asked to pick two folders: one with the original photo
// files (photos are matched by their original filename, searched recursively through subfolders
// too), and one to save the finished PSD into.
//
// Beta limitations: only photo placement (cover-fit crop centered on the focal point) is built so
// far. Masks, frames/borders, shadows, rotation, and text elements on this page are not yet
// translated into script instructions — a summary alert at the end lists what was skipped.

app.preferences.rulerUnits = Units.PIXELS;

var PAGE = ${pageJson};

// Searches the chosen folder AND every subfolder underneath it (many photographers keep originals
// split into per-session subfolders rather than one flat folder) — case-insensitively, since a
// file's case can drift across an OS move/re-download even though the name is otherwise identical.
function findSourceFile(folder, filename) {
  var target = filename.toLowerCase();
  var entries = folder.getFiles();
  var subfolders = [];
  for (var i = 0; i < entries.length; i++) {
    var entry = entries[i];
    if (entry instanceof Folder) {
      subfolders.push(entry);
    } else if (entry.name.toLowerCase() === target) {
      return entry;
    }
  }
  for (var j = 0; j < subfolders.length; j++) {
    var found = findSourceFile(subfolders[j], filename);
    if (found !== null) return found;
  }
  return null;
}

// Adds a layer mask that reveals only the given rectangle — the classic scripting DOM has no
// direct "add layer mask from selection" method, so this replays the ActionManager call Photoshop
// itself records for Layer > Layer Mask > Reveal Selection (stable since Photoshop CS2).
function maskLayerToSelection(doc) {
  var idMk = charIDToTypeID("Mk  ");
  var desc = new ActionDescriptor();
  var idNw = charIDToTypeID("Nw  ");
  var idChnl = charIDToTypeID("Chnl");
  desc.putClass(idNw, idChnl);
  var idAt = charIDToTypeID("At  ");
  var ref = new ActionReference();
  var idMsk = charIDToTypeID("Msk ");
  ref.putEnumerated(idChnl, idChnl, idMsk);
  desc.putReference(idAt, ref);
  var idUsng = charIDToTypeID("Usng");
  var idUsrM = charIDToTypeID("UsrM");
  var idRvlS = charIDToTypeID("RvlS");
  desc.putEnumerated(idUsng, idUsrM, idRvlS);
  executeAction(idMk, desc, DialogModes.NO);
}

// Places one photo into the page, cropped to exactly fill (xPx,yPx,wPx,hPx) the same way
// object-fit:cover + object-position does in the web editor: scale up to the larger of the two
// axis ratios, then shift so the focal point stays centered in whichever axis overflows.
function placeCoverFit(doc, file, xPx, yPx, wPx, hPx, focalXPct, focalYPct) {
  var srcDoc = app.open(file);
  var srcW = srcDoc.width.as("px");
  var srcH = srcDoc.height.as("px");
  srcDoc.selection.selectAll();
  srcDoc.selection.copy();
  srcDoc.close(SaveOptions.DONOTSAVECHANGES);

  app.activeDocument = doc;
  doc.paste();
  var layer = doc.activeLayer;

  var bounds = layer.bounds;
  var curLeft = bounds[0].as("px");
  var curTop = bounds[1].as("px");
  layer.translate(-curLeft, -curTop);

  var scale = Math.max(wPx / srcW, hPx / srcH);
  layer.resize(scale * 100, scale * 100, AnchorPosition.TOPLEFT);

  var scaledW = srcW * scale;
  var scaledH = srcH * scale;
  var targetX = xPx - (scaledW - wPx) * (focalXPct / 100);
  var targetY = yPx - (scaledH - hPx) * (focalYPct / 100);
  layer.translate(targetX, targetY);

  var region = [
    [xPx, yPx],
    [xPx + wPx, yPx],
    [xPx + wPx, yPx + hPx],
    [xPx, yPx + hPx]
  ];
  doc.selection.select(region);
  maskLayerToSelection(doc);
  doc.selection.deselect();
}

(function run() {
  var sourceFolder = Folder.selectDialog("בחרו את התיקייה עם קבצי התמונות המקוריים");
  if (sourceFolder === null) {
    alert("בוטל — לא נבחרה תיקיית מקור.");
    return;
  }
  var outputFolder = Folder.selectDialog("לאן לשמור את קובץ ה-PSD?");
  if (outputFolder === null) {
    alert("בוטל — לא נבחרה תיקיית שמירה.");
    return;
  }

  // Passed as explicit UnitValue objects, not plain numbers — documents.add() is a known
  // ExtendScript trap where plain width/height numbers get silently reinterpreted (sometimes even
  // swapped) depending on Photoshop's own New Document preset/units state, regardless of the
  // rulerUnits preference set above. UnitValue leaves no ambiguity for Photoshop to get wrong.
  var widthUV = UnitValue(PAGE.widthPx, "px");
  var heightUV = UnitValue(PAGE.heightPx, "px");
  var doc = app.documents.add(widthUV, heightUV, PAGE.dpi, PAGE.pageLabel, NewDocumentMode.RGB, DocumentFill.WHITE, 1);

  // Belt-and-suspenders: if the canvas Photoshop actually created doesn't match what was asked for
  // (including a swapped width/height), force it back to the exact requested size rather than
  // silently continuing on a wrong-shaped page.
  var actualW = doc.width.as("px");
  var actualH = doc.height.as("px");
  if (Math.abs(actualW - PAGE.widthPx) > 1 || Math.abs(actualH - PAGE.heightPx) > 1) {
    doc.resizeCanvas(widthUV, heightUV, AnchorPosition.MIDDLECENTER);
  }

  var placedCount = 0;
  var missingFiles = [];
  for (var i = 0; i < PAGE.elements.length; i++) {
    var el = PAGE.elements[i];
    var file = findSourceFile(sourceFolder, el.filename);
    if (file === null) {
      missingFiles.push(el.filename);
      continue;
    }
    var xPx = (el.xPct / 100) * PAGE.widthPx;
    var yPx = (el.yPct / 100) * PAGE.heightPx;
    var wPx = (el.widthPct / 100) * PAGE.widthPx;
    var hPx = (el.heightPct / 100) * PAGE.heightPx;
    placeCoverFit(doc, file, xPx, yPx, wPx, hPx, el.focalX, el.focalY);
    doc.activeLayer.name = el.filename;
    placedCount++;
  }

  var saveFile = new File(outputFolder.fsName + "/" + PAGE.pageLabel + ".psd");
  var psdOpts = new PhotoshopSaveOptions();
  psdOpts.layers = true;
  doc.saveAs(saveFile, psdOpts, true);

  var summary = "נשמר: " + saveFile.fsName + "\\n\\nהונחו " + placedCount + " מתוך " + PAGE.elements.length + " תמונות.";
  if (missingFiles.length > 0) {
    summary += "\\n\\nלא נמצאו בתיקייה (" + missingFiles.length + "): " + missingFiles.join(", ");
  }
  if (PAGE.skippedExtrasCount > 0) {
    summary += "\\n\\n" + PAGE.skippedExtrasCount + " מהתמונות שהונחו כללו מסכה/מסגרת/צל/סיבוב בעורך — עדיין לא נתמך בסקריפט, הונחו בלי האפקט.";
  }
  if (PAGE.skippedTextCount > 0) {
    summary += "\\n\\n" + PAGE.skippedTextCount + " אלמנטים של טקסט בעמוד זה עדיין לא נתמכים ולא נוספו.";
  }
  alert(summary);
})();
`;
}
