// Illustrated number elements for the magnet-frame designer ("ספרות" tab): static PNGs generated by
// scripts/magnet-digits/generate.mjs into public/magnet-elements/digits. They're added and exported
// exactly like the watercolor florals (a decoration element with `floralId`), so
// findMagnetFrameFloral resolves these ids too.
import type { MagnetFrameFloral } from "@/lib/magnetFrameFlorals";

const ALL = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"];
const TO_TEN = ALL.slice(0, 11);

export const MAGNET_DIGIT_STYLES: { key: string; label: string; numbers: string[] }[] = [
  { key: "gold", label: "זהב וכסף", numbers: ALL },
  { key: "balloon", label: "מסיבה", numbers: ALL },
  { key: "cake", label: "עוגה", numbers: ALL },
  { key: "swirl", label: "מסולסל", numbers: TO_TEN },
  { key: "rainbow", label: "צבע מתחלף", numbers: TO_TEN },
  { key: "threeD", label: "תלת מימד", numbers: TO_TEN },
  { key: "batmitzva", label: "בת מצווה", numbers: ALL },
  { key: "barmitzva", label: "בר מצווה", numbers: ALL },
];

export const magnetDigitId = (style: string, n: string) => `digit-${style}-${n}`;

export const MAGNET_FRAME_DIGITS: MagnetFrameFloral[] = MAGNET_DIGIT_STYLES.flatMap((s) =>
  s.numbers.map((n) => ({ id: magnetDigitId(s.key, n), label: `${s.label} ${n}`, url: `/magnet-elements/digits/${s.key}-${n}.png` }))
);
