// Illustrated number elements for the magnet-frame designer ("ספרות" tab): static PNGs generated by
// scripts/magnet-digits/generate.mjs into public/magnet-elements/digits. They're added and exported
// exactly like the watercolor florals (a decoration element with `floralId`), so
// findMagnetFrameFloral resolves these ids too.
import type { MagnetFrameFloral } from "@/lib/magnetFrameFlorals";

export const MAGNET_DIGIT_NUMBERS = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "12", "13"];

export const MAGNET_DIGIT_STYLES: { key: string; label: string }[] = [
  { key: "gold", label: "זהב וכסף" },
  { key: "balloon", label: "בלון מסיבה" },
  { key: "cake", label: "עוגה" },
  { key: "animals", label: "חיות" },
  { key: "batmitzva", label: "בת מצווה" },
  { key: "barmitzva", label: "בר מצווה" },
];

export const magnetDigitId = (style: string, n: string) => `digit-${style}-${n}`;

export const MAGNET_FRAME_DIGITS: MagnetFrameFloral[] = MAGNET_DIGIT_STYLES.flatMap((s) =>
  MAGNET_DIGIT_NUMBERS.map((n) => ({ id: magnetDigitId(s.key, n), label: `${s.label} ${n}`, url: `/magnet-elements/digits/${s.key}-${n}.png` }))
);
