import type { SupabaseClient } from "@supabase/supabase-js";
import renderWorkerHash from "@/lib/generated/renderWorkerHash.json";
import type { WorkerStatusRow } from "@/lib/types";

// Generated by scripts/computeRenderHash.js as this app's own "prebuild" step (package.json) — a
// fingerprint of the exact render-pipeline files this Vercel deployment was built from. The Fly
// worker image bakes the SAME fingerprint in via the identical script (Dockerfile.worker) and
// reports it here on every poll tick; comparing the two is the whole staleness check below.
export const EXPECTED_WORKER_CODE_HASH: string = (renderWorkerHash as { hash: string }).hash;

// A poll tick fires every 4s (worker/src/index.ts) — 30s is generous headroom past a single missed
// tick (a slow render blocks the loop until it finishes, so a REAL export in progress can silently
// widen this gap; deliberately loose to avoid false positives during a long single-job render) while
// still catching a genuinely crashed/stopped machine within a reasonable time.
const MAX_HEARTBEAT_AGE_MS = 5 * 60 * 1000;

export type RenderWorkerHealth = { ok: true } | { ok: false; reason: string };

// Checked once, right before a new PDF export job is created (export-pdf/route.ts) — never after
// a job already exists, since an export already `pending`/`processing` should always be picked up
// eventually by whatever worker comes back, stale or not; this only guards against STARTING a new
// one that a stale-code or dead worker would render with outdated logic (or never pick up at all).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export async function checkRenderWorkerHealth(supabase: SupabaseClient<any>): Promise<RenderWorkerHealth> {
  const { data: status } = await supabase
    .from("worker_status")
    .select("*")
    .eq("id", 1)
    .maybeSingle<WorkerStatusRow>();

  if (!status) {
    return { ok: false, reason: "שרת הרינדור עדיין לא דיווח על עצמו — ייתכן שהוא עדיין עולה, נסו שוב בעוד רגע." };
  }

  const heartbeatAgeMs = Date.now() - new Date(status.last_heartbeat_at).getTime();
  if (heartbeatAgeMs > MAX_HEARTBEAT_AGE_MS) {
    return { ok: false, reason: "שרת הרינדור לא זמין כרגע (לא הגיב יותר מדי זמן) — נסו שוב בעוד כמה דקות." };
  }

  if (status.code_hash !== EXPECTED_WORKER_CODE_HASH) {
    return {
      ok: false,
      reason: "שרת הרינדור עדיין לא עודכן לגרסה האחרונה של המערכת — נסו שוב בעוד כמה דקות, ואם זה נמשך יש לפרוס אותו מחדש (fly deploy).",
    };
  }

  return { ok: true };
}
